spring:
  application:
    name: eureka-hystrix
  main:
    allow-bean-definition-overriding: true
server:
  port: 9004
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:9001/eureka/
    registry-fetch-interval-seconds: 30


