spring:
  application:
    name: eureka-server
  main:
    allow-bean-definition-overriding: true
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

